### ISSUE TITLE
Script Error   Invalid Syntax

### ISSUE THREAD

**Issue by 0NDevil** [Marv2190/venus.dbus-MqttToGridMeter#3]
Hi, 
i installed the script but not working :(

> root@raspberrypi2:/data/mqtttogrid# python /data/mqtttogrid/MQTTtoGridMeter.py
> Traceback (most recent call last):
>   File "/data/mqtttogrid/MQTTtoGridMeter.py", line 33, in <module>
>     from vedbus import VeDbusService
>   File "/data/mqtttogrid/vedbus.py", line 8
>     <!DOCTYPE html>
>     ^
> SyntaxError: invalid syntax

ok. my fault
copy of "ve_utils.py" and "vedbus.py"  was faulty.

Now the script run`s but i get no value in mqttMeter

Here is mqtt Messsage what i get with mqtt FX from the Tasmota SmartMeter:
`{"Time":"2022-12-24T14:29:58","SML":{"Power_cur":545.00,"Total_HT_in":2967.81,"Total_NT_in":2082.40,"Total_in":5050.21}}`

i have the syntax "SML" in it (need it for Soyosource Controller)   -is this a problem?
My SmartMeter don`t show values for "total_out"

> INFO:root:House Consumption: 0
> ERROR:root:Programm MQTTtoMeter ist abgestuerzt. (on message Funkion)
> Traceback (most recent call last):
>   File "/data/mqtttogrid/MQTTtoGridMeter.py", line 91, in on_message
>     powercurr = float(jsonpayload["Zaehler"]["Power_curr"])
> KeyError: 'Zaehler'
> 'Zaehler'
> Im MQTTtoMeter Programm ist etwas beim auslesen der Nachrichten schief gegangen

I hope someone could help me.   (gerne auch auf Deutsch)

**Comment by 0NDevil** [comment]
ok solved, i figured it out.
Because the SML Object in my mqtt message / jsonpayload  i have to edit the key ["Zaehler"] to ["SML"]  

Now i have to find out how to modify tasmota to send every 2 or 3 second with my version tele period only 10sec.

**Comment by Marv2190** [comment]
Just and little late add, in the Script use ",16", then it will send everytime new Data arrived.
